# Generated by Django 4.2.20 on 2025-03-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
