# Generated by Django 4.2.20 on 2025-03-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0002_alter_song_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='next_due_date',
            field=models.DateField(null=True),
        ),
    ]
