# Generated by Django 4.2.20 on 2025-03-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_alter_song_options_song_bpm_song_next_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='bpm',
        ),
        migrations.AddField(
            model_name='song',
            name='target_bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
