# Generated by Django 4.2.20 on 2025-03-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0004_remove_song_bpm_song_target_bpm_alter_song_arranger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
